// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// piecewise_regression
Rcpp::List piecewise_regression(Rcpp::IntegerVector x, Rcpp::NumericVector y, Rcpp::IntegerVector bps, std::string fit_type);
RcppExport SEXP _StrataFinder_piecewise_regression(SEXP xSEXP, SEXP ySEXP, SEXP bpsSEXP, SEXP fit_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type bps(bpsSEXP);
    Rcpp::traits::input_parameter< std::string >::type fit_type(fit_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(piecewise_regression(x, y, bps, fit_type));
    return rcpp_result_gen;
END_RCPP
}
// precompute_ssr_mat
std::vector<std::vector<double>> precompute_ssr_mat(Rcpp::IntegerVector x, Rcpp::NumericVector y, std::string fit_type);
RcppExport SEXP _StrataFinder_precompute_ssr_mat(SEXP xSEXP, SEXP ySEXP, SEXP fit_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< std::string >::type fit_type(fit_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(precompute_ssr_mat(x, y, fit_type));
    return rcpp_result_gen;
END_RCPP
}
// get_breakpoints
Rcpp::List get_breakpoints(Rcpp::IntegerVector x, Rcpp::NumericVector y, int n_bp, std::string fit_type, int min_len, std::vector<std::vector<double>> ssr_mat);
RcppExport SEXP _StrataFinder_get_breakpoints(SEXP xSEXP, SEXP ySEXP, SEXP n_bpSEXP, SEXP fit_typeSEXP, SEXP min_lenSEXP, SEXP ssr_matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type n_bp(n_bpSEXP);
    Rcpp::traits::input_parameter< std::string >::type fit_type(fit_typeSEXP);
    Rcpp::traits::input_parameter< int >::type min_len(min_lenSEXP);
    Rcpp::traits::input_parameter< std::vector<std::vector<double>> >::type ssr_mat(ssr_matSEXP);
    rcpp_result_gen = Rcpp::wrap(get_breakpoints(x, y, n_bp, fit_type, min_len, ssr_mat));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_StrataFinder_piecewise_regression", (DL_FUNC) &_StrataFinder_piecewise_regression, 4},
    {"_StrataFinder_precompute_ssr_mat", (DL_FUNC) &_StrataFinder_precompute_ssr_mat, 3},
    {"_StrataFinder_get_breakpoints", (DL_FUNC) &_StrataFinder_get_breakpoints, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_StrataFinder(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
