# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Estimate the equation parameters and residuals for each piece of the data
#' @param x x values
#' @param y y values
#' @param bps breakpoint indices
#' @param fit_type type of equation to fit (linear, exponential, or quadratic)
#' @return a named list of the intercept, coefficients, sum squared residuals, and residual values for each segment
piecewise_regression <- function(x, y, bps, fit_type) {
    .Call(`_StrataFinder_piecewise_regression`, x, y, bps, fit_type)
}

#' Compute the sum squared residuals matrix
#' @param x x values
#' @param y yvalues
#' @param fit_type the type of equation to fit (linear, exponential, or quadratic)
#' @return sum squared residual matrix
precompute_ssr_mat <- function(x, y, fit_type) {
    .Call(`_StrataFinder_precompute_ssr_mat`, x, y, fit_type)
}

#' Get the breakpoint locations for the given x and y values, and given parameters
#' @param x x values
#' @param y y values
#' @param n_bps number of breakpoints to estimate
#' @param fit_type type of equation to fit (linear, exponential, or quadratic)
#' @param min_len the minimum number of x values between breakpoints
#' @param ssr_mat the sum squared residuals matrix
#' @return a named list where bps is the breakpoint indices and ssr is a list of ssr values for each segment
get_breakpoints <- function(x, y, n_bp, fit_type, min_len, ssr_mat) {
    .Call(`_StrataFinder_get_breakpoints`, x, y, n_bp, fit_type, min_len, ssr_mat)
}

